version: '3'

services:
  web:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: PatrolsProject
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/usr/src/app
    environment:
      IN_DOCKER: 1
    ports:
    - "8000:8000"